language: node_js
node_js:
  - lts/dubnium
  - node
after_success: bash <(curl -s https://codecov.io/bash)
deploy:
  provider: releases
  skip_cleanup: true
  api_key:
    secure: hAXH6qtC2z55WaH9LlBWJlia654WNw68gGOcsx3YvJy+TZSA3kAuCgEfiN/vM1HfRtzGthfWkCqCgJYgLS1q0+0ZuOZx4iLhazKuBcnVqjErHXSYffl2H8+5cKxMEa2hhpBp1/OXCmYNDI6D5Xq25yt/I6tPRjhZPeBbP0oKDyk=
  file:
    - 'nlcst-to-string.js'
    - 'nlcst-to-string.min.js'
  on:
    tags: true
